apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-properties
        optional: false
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cluster-properties
    namespace: flux-system
    envs:
      - ./properties/cluster.properties
