# replicas-patch.yaml

# 1. Grafana Deployment Patch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prometheus-stack-grafana
spec:
  replicas: 1
---
# 2. Alertmanager CR Patch
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: kube-prometheus-stack-alertmanager
spec:
  replicas: 1
---
# 3. Prometheus CR Patch
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
spec:
  replicas: 1

